#!/usr/bin/env bash
set -euo pipefail

declare -a require=(
  "sway-util" # shellcheck source ./sway-util
)

# setup {{{
[[ ! -v _I3WG_UTIL ]] || return
[[ "${BASH_SOURCE[0]}" != "$0" ]] || {
  echo "$0: this script should be sourced, not be called directly" >&2
  exit 1
}
declare -x _I3WG_UTIL

declare -g basedir libdir
basedir="$(realpath -e "$(dirname "${BASH_SOURCE[0]}")")"
libdir="${LIBDIR:-$(realpath -e "${basedir}/../lib/")}"

for lib in "${require[@]}"; do
  [[ -e "$lib" ]] || {
    lib="$libdir/$lib"
    [[ -e "$lib" ]] || {
      echo "lib not found: $lib" >&2
      exit 1
    }
  }
  # shellcheck disable=1090
  source "$lib" &> /dev/null || {
    echo "failed sourcing lib: $lib" >&2
    exit 1
  }
done
# }}}

declare -x I3WG="${I3WG:-i3-workspace-groups}"
command_exists "$I3WG" || {
  echo "command not found: $I3WG" >&2
  exit 1
}

declare -x I3WG_SELECT="${I3WG_SELECT:-$LIBDIR/i3wg-select}"
command_exists "$I3WG_SELECT" || {
  echo "command not found: $I3WG_SELECT" >&2
  exit 1
}

# The default group name is the empty string, so in order to make it clearer we
# replace it with this string when presenting it to the user.
declare -x DEFAULT_GROUP_ITEM="${DEFAULT_GROUP_ITEM:-<default>}"
