#!/usr/bin/env bash
set -euo pipefail

declare -a require=(
  "i3wg-util" # shellcheck source ./i3wg-util
)

# setup {{{
[[ ! -v _I3WG_SELECT ]] || return
declare -x _I3WG_SELECT

declare -g basedir libdir
basedir="$(realpath -e "$(dirname "${BASH_SOURCE[0]}")")"
libdir="${LIBDIR:-$(realpath -e "${basedir}")}"

for lib in "${require[@]}"; do
  [[ -e "$lib" ]] || {
    lib="$libdir/$lib"
    [[ -e "$lib" ]] || {
      echo "lib not found: $lib" >&2
      exit 1
    }
  }
  # shellcheck disable=1090
  source "$lib" &> /dev/null || {
    echo "failed sourcing lib: $lib" >&2
    exit 1
  }
done
# }}}

function i3wg-selector() {
  local select_type="$1"
  local select_msg="$2"
  sel="$(rofi -dmenu -i -p "$select_msg" -lines 10 -width 30)" || return 1
  if [[ "$select_type" == "groups" && "$sel" == "$DEFAULT_GROUP_ITEM" ]]; then
    sel=""
  fi
  echo "$sel"
}

function i3wg-run-select() {
  local select_type
  local select_msg
  while getopts ":gwm:" OPT; do
    case "$OPT" in
    g | w)
      if [[ -v select_type ]]; then
        echo "error: -g and/or -w can be passed only once" >&2
        return 1
      fi
      ;;&
    g)
      select_type="groups"
      ;;
    w)
      select_type="workspaces"
      ;;
    m)
      select_msg="$OPTARG"
      ;;
    \?)
      break
      ;;
    esac
  done
  shift $((OPTIND - 1))

  select_type="${select_type:-groups}"

  case "$select_type" in
  groups)
    select_msg="${select_msg:-Select workspace group}"
    ;;
  workspaces)
    select_msg="${select_msg:-Select workspace}"
    ;;
  *)
    echo "error: unknown selection type '$select_type'" >&2
    return 1
    ;;
  esac

  declare -a choices=()
  local items
  items="$("$I3WG" "list-${select_type}" "$@")" || return $?
  for item in $items; do
    if [[ "$select_type" == "groups" && "$item" == "" ]]; then
      continue
    fi
    choices+=("${item}")
  done
  if [[ "$select_type" == "groups" ]]; then
    choices+=("${DEFAULT_GROUP_ITEM}")
  fi
  i3wg-selector "$select_type" "$select_msg" <<< "$(printf '%s\n' "${choices[@]}")"
}

function i3wg-select-group() {
  i3wg-run-select -g "$@"
}

function i3wg-select-workspace() {
  i3wg-run-select -w "$@"
}

# if script is run directly (not sourced), call select
if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  i3wg-run-select "$@"
fi
